version: '3.6'
services:
  mysql8:
    image: mysql:8.0.13
    container_name: mysql8
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./storage/files:/var/lib/mysql-files
      - ./storage/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.d:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
