server {
    listen 80;
    server_name s3.local;

    # 限制上传文件大小，避免 LobeHub 上传大图失败
    client_max_body_size 100M;

    location / {
        proxy_pass http://127.0.0.1:9800; # 指向你映射出来的 rustfs 端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
