version: "3"

services:
  server:
    image: gitea/gitea:1.17.3-rootless
    environment:
      - USER_UID=1000         # set app.ini BUILTIN_SSH_SERVER_USER=`id -u`
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    volumes:
      - ./config:/etc/gitea   # config 目录需为指定的 UID/GID 的用户/组拥有
      - ./data:/var/lib/gitea # data 目录需为指定的 UID/GID 的用户/组拥有
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:7000:3000" # set app.ini ROOT_URL=http://localhost:7000/
      - "127.0.0.1:7222:22"   # set app.ini SSH_PORT=7222 SSH_LISTEN_PORT=22 
    depends_on:
      - db

  db:
    image: mysql:8.0.13
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    ports:
      - "127.0.0.1:7306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
